version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env

  dbup:
    build:
      context: dbup
      dockerfile: ./Dockerfile
    depends_on:
      - database
    env_file:
      - .env
    restart: on-failure

  apollo:
    build:
      context: apollo
      dockerfile: ./Dockerfile
    depends_on:
      - database
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST_DOCKER: 'database'